# ===============================
# Application
# ===============================
spring.application.name=RevPay
server.port=9990

# ===============================
# Oracle Database Configuration
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=vishnu
spring.datasource.password=vishnu123

# ===============================
# HikariCP 
# ===============================
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false

# ===============================
# Security (Default Login)
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# folder to store loan documents
loan.upload.dir=uploads/loans

