# ===============================
# Application
# ===============================
spring.application.name=RevPay
server.port=9990

# ===============================
# Oracle Database Configuration
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=vishnu
spring.datasource.password=vishnu123
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# HikariCP (Keep small for XE)
# ===============================
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false

# ===============================
# Security (Default Login)
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.revpay=DEBUG